Only check if docker login works when pushing towards docker.io

diff --git a/bin/pymdocker b/bin/pymdocker
--- a/bin/pymdocker
+++ b/bin/pymdocker
@@ -211,15 +211,18 @@ fi
 if [ ! -z "$DO_PUSH" ]; then
     # NOTE: for this to work, the running user must have logged in into the
     # docker hub using 'docker login'
-    echo "=> Checking if 'docker login' has been run"
-    set +e
-    IS_LOGGEDIN=$(docker info | grep Username)
-    if [ -z "$DO_DEBUG" ]; then
-        set -e
-    fi
-    if [ -z "$IS_LOGGEDIN" ]; then
-        echo "ERROR: please login to docker hub with 'docker login'"
-        exit 1
+
+    if [[ "$REGISTRY" =~ ^(docker.io)$ ]]; then
+        echo "=> Checking if 'docker login' has been run"
+        set +e
+        IS_LOGGEDIN=$(docker info | grep Username)
+        if [ -z "$DO_DEBUG" ]; then
+            set -e
+        fi
+        if [ -z "$IS_LOGGEDIN" ]; then
+            echo "ERROR: please login to docker hub with 'docker login'"
+            exit 1
+        fi
     fi
 
     echo "=> Pushing to registry ${DOCKER_REPO}:${VERSION}"
